### ISSUE TITLE
Encounter error when run multi-semantic-release

### ISSUE THREAD

**Issue by luokuning** [dhoulb/multi-semantic-release#120]
When running `multi-semantic-release`, sometimes it will encounter the following errors (`main` branch)

And I noticed that the `analyzeCommits` phase is missing, which caused this error.

I'm using version `v2.13.0` of multi-semantic-release

```
[11:17:30 AM] [stepper] › ✔  Allowed to push to the Git repository
[11:17:30 AM] [stepper] › ℹ  Start step "verifyConditions" of plugin "Inline plugin"
[11:17:30 AM] [stepper] › ✔  Completed step "verifyConditions" of plugin "Inline plugin"
[11:17:30 AM] [stepper] › ℹ  Found 3 commits since last release
[11:17:30 AM] [stepper] › ℹ  Start step "generateNotes" of plugin "Inline plugin"
[11:17:30 AM] [stepper] › ✖  Failed step "generateNotes" of plugin "Inline plugin"
[11:17:30 AM] [stepper] › ✖  An error occurred while running semantic-release: TypeError: Cannot read properties of undefined (reading 'filter')
    at generateNotes (node_modules/multi-semantic-release/lib/createInlinePluginCreator.js:209:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async validator (node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as generateNotes] (node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (node_modules/semantic-release/index.js:110:27)
    at async module.exports (node_modules/semantic-release/index.js:260:22)
    at async releasePackage (node_modules/multi-semantic-release/lib/multiSemanticRelease.js:201:15)
    at async Promise.all (index 0) {
  pluginName: 'Inline plugin'
}
```

**Comment by antongolub** [comment]
It's hard to tell what exactly may cause the issue. Try using `--sequential-init` to get a more _predictable_ flow. Hope this helps.

**Comment by luokuning** [comment]
After correcting all of the versions of semantic-release and its plugins, there are no more errors. I believe there is nothing to do with the multi-semantic-release.
