### ISSUE TITLE
Failed step "prepare" of plugin "Inline plugin"

### ISSUE THREAD

**Issue by Th3S4mur41** [dhoulb/multi-semantic-release#131]
Release has been failing lately with the following error. 

```
ℹ  Start step "prepare" of plugin "Inline plugin"
@scope/components
v1.0.0-beta.26
npm ERR! Cannot set properties of null (setting 'parent')

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2022-09-13T00_31_33_7[95](https://github.com/atos-parallel/web/actions/runs/3041448790/jobs/4898728743#step:8:96)Z-debug-0.log
[12:31:38 AM] [@scope/components] › ✖  Failed step "prepare" of plugin "Inline plugin"
[12:31:38 AM] [@scope/components] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: npm version 1.0.0-beta.26 --userconfig /tmp/5f7530311c1b7a10f54d7b30db3e7c4c/.npmrc --no-git-tag-version --allow-same-version
npm ERR! Cannot set properties of null (setting 'parent')

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2022-09-13T00_31_33_795Z-debug-0.log
@scope/components
v1.0.0-beta.26
    at makeError (/__w/web/web/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/__w/web/web/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:[96](https://github.com/***/actions/runs/3041448790/jobs/4898728743#step:8:97):5)
    at async module.exports (/__w/web/web/node_modules/@semantic-release/npm/lib/prepare.js:22:3)
    at async prepare (/__w/web/web/node_modules/@semantic-release/npm/index.js:68:3)
    at async validator (/github/home/.npm/_npx/fc5f6a55a6a495a8/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /github/home/.npm/_npx/fc5f6a55a6a495a8/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/github/home/.npm/_npx/fc5f6a55a6a495a8/node_modules/p-reduce/index.js:16:18) {
  shortMessage: 'Command failed with exit code 1: npm version 1.0.0-beta.26 --userconfig /tmp/5f7530311c1b7a10f54d7b30db3e7c4c/.npmrc --no-git-tag-version --allow-same-version',
  command: 'npm version 1.0.0-beta.26 --userconfig /tmp/5f7530311c1b7a10f54d7b30db3e7c4c/.npmrc --no-git-tag-version --allow-same-version',
  escapedCommand: 'npm version 1.0.0-beta.26 --userconfig "/tmp/5f7530311c1b7a10f54d7b30db3e7c4c/.npmrc" --no-git-tag-version --allow-same-version',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '@scope/components\nv1.0.0-beta.26',
  stderr: "npm ERR! Cannot set properties of null (setting 'parent')\n" +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /github/home/.npm/_logs/2022-09-13T00_31_33_795Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: 'Inline plugin'
}
[multi-semantic-release]: Error: Command failed with exit code 1: npm version 1.0.0-beta.26 --userconfig /tmp/5f7530311c1b7a10f54d7b30db3e7c4c/.npmrc --no-git-tag-version --allow-same-version
npm ERR! Cannot set properties of null (setting 'parent')

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2022-09-13T00_31_33_795Z-debug-0.log
@atos-parallel/components
v1.0.0-beta.26
    at makeError (/__w/web/web/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/__w/web/web/node_modules/execa/index.js:[118](https://github.com/***/actions/runs/3041448790/jobs/4898728743#step:8:119):26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/__w/web/web/node_modules/@semantic-release/npm/lib/prepare.js:22:3)
    at async prepare (/__w/web/web/node_modules/@semantic-release/npm/index.js:68:3)
    at async validator (/github/home/.npm/_npx/fc5f6a55a6a495a8/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /github/home/.npm/_npx/fc5f6a55a6a495a8/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/github/home/.npm/_npx/fc5f6a55a6a495a8/node_modules/p-reduce/index.js:16:18) {
  shortMessage: 'Command failed with exit code 1: npm version 1.0.0-beta.26 --userconfig /tmp/5f7530311c1b7a10f54d7b30db3e7c4c/.npmrc --no-git-tag-version --allow-same-version',
  command: 'npm version 1.0.0-beta.26 --userconfig /tmp/5f7530311c1b7a10f54d7b30db3e7c4c/.npmrc --no-git-tag-version --allow-same-version',
  escapedCommand: 'npm version 1.0.0-beta.26 --userconfig "/tmp/5f7530311c1b7a10f54d7b30db3e7c4c/.npmrc" --no-git-tag-version --allow-same-version',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '@scope/components\nv1.0.0-beta.26',
  stderr: "npm ERR! Cannot set properties of null (setting 'parent')\n" +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /github/home/.npm/_logs/2022-09-13T00_31_33_795Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: 'Inline plugin'
}
Error: Process completed with exit code 1.
```

Last successful run was on September 7th, 2022. Unfortunately, CI logs for the last successful run are no longer available, so it's not possible to double check if the details.

Between the last successful run and the failed run, only 4 dev dependencies were updated to a newer patch.

[multi-semantic-release](https://github.com/dhoulb/multi-semantic-release) however is not installed as dependency but runs on CI with `npx multi-semantic-release`
So its version might have changed in-between

Release is configured with the following settings:

```json
{
	"branches": ["main", "next", { "name": "beta", "prerelease": true }, { "name": "alpha", "prerelease": true }],
	"plugins": [
		[
			"@semantic-release/commit-analyzer",
			{
				"preset": "conventionalcommits",
				"releaseRules": [
					{
						"type": "build",
						"scope": "deps",
						"release": "patch"
					}
				]
			}
		],
		[
			"@semantic-release/release-notes-generator",
			{
				"preset": "conventionalcommits",
				"presetConfig": {
					"types": [
						{
							"type": "feat",
							"section": "Features"
						},
						{
							"type": "fix",
							"section": "Bug Fixes"
						},
						{
							"type": "build",
							"section": "Dependencies and Other Build Updates",
							"hidden": false
						}
					]
				}
			}
		],
		"@semantic-release/changelog",
		"@semantic-release/npm",
		[
			"@semantic-release/git",
			{
				"assets": ["CHANGELOG.md", "package.json", "package-lock.json"]
			}
		],
		"@semantic-release/github"
	]
}
```

Any idea what is going wrong?

**Comment by Th3S4mur41** [comment]
In the meantime I tried downgrading multi-semantic-release to 2.13.0 but the issue persists
