### ISSUE TITLE
Unable to run all tests locally

### ISSUE THREAD

**Issue by mmeester** [dhoulb/multi-semantic-release#140]
Some tests seem to fail when trying to run git commands, any idea how to get this to work on a MacOS device?

```
 FAIL  test/lib/git.test.js
  ● Fetch all tags on master after two package release

    Command failed with exit code 128: git fetch --tags file:///private/var/folders/h2/4nn58mvx1597_n_d7fg1xdxm0000gn/T/1a05b43f7c313ebdcf89c218302008d7
    fatal: couldn't find remote ref HEAD

      199 | 	// Call semanticRelease() on the directory and save result to pkg.
      200 | 	// Don't need to log out errors as semantic-release already does that.
    > 201 | 	pkg.result = await semanticRelease(options, {
          | 	             ^
      202 | 		cwd: dir,
      203 | 		env,
      204 | 		stdout: new RescopedStream(stdout, name),

      at makeError (node_modules/semantic-release/node_modules/execa/lib/error.js:60:11)
      at handlePromise (node_modules/semantic-release/node_modules/execa/index.js:118:26)
      at fetch (node_modules/semantic-release/lib/git.js:120:5)
      at node_modules/semantic-release/lib/branches/index.js:21:5
      at pEachSeries (node_modules/p-each-series/index.js:8:3)
      at Object.<anonymous>.module.exports (node_modules/semantic-release/lib/branches/index.js:20:3)
      at run (node_modules/semantic-release/index.js:65:22)
      at Object.<anonymous>.module.exports (node_modules/semantic-release/index.js:269:22)
      at releasePackage (lib/multiSemanticRelease.js:201:15)
```

**Comment by antongolub** [comment]
Hope #39 could fix the issue.

**Comment by mmeester** [comment]
I'm not really sure what the relation is here, but let's see
