### ISSUE TITLE
Ability to release maintenance branches 

### ISSUE THREAD

**Issue by musaabal-okaidi** [dhoulb/multi-semantic-release#27]
Hi

Do you know if it's possible to make maintenance releases using `multi-semantic-release`?
https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/maintenance-releases.md

I've tried a few things with no luck. I can share the issues I'm getting, but before doing so I want to ask the question to find out if that's even possible?

**Comment by antongolub** [comment]
It is interesting. What does **semrel** if it finds, for example, several `feat` commits in `1.x` and `2.x` branches?

**Comment by musaabal-okaidi** [comment]
From the minimal testing I've done, you're supposed to run **semrel** on the maintenance branch directly, and when it runs, it will run in the context of that branch only. The process worked for me when I ran it in the root of the repo directly, but when I tried to run **semrel** inside the packages I go this error which doesn't really make sense:

```
[11:05:08] [semantic-release] › ℹ  Found git tag onceperappperenvironment@1.7.0 associated with version 1.7.0 on branch onceperappperenvironment@1.7.x
[11:05:08] [semantic-release] › ℹ  Found 1 commits since last release
[11:05:08] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:05:08] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(fds): fds
[11:05:08] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[11:05:08] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 1 commits complete: patch release
[11:05:08] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:05:08] [semantic-release] › ℹ  The next release version is 1.7.1
[11:05:08] [semantic-release] › ✖  EINVALIDNEXTVERSION The release `1.7.1` on branch `onceperappperenvironment@1.7.x` cannot be published as it is out of range.
Based on the releases published on other branches, only versions within the range >=1.7.0 <1.5.1 can be published from branch onceperappperenvironment@1.7.x.

The following commit is responsible for the invalid release:

    * fix(fds): fds (3c2b394)

This commit should be moved to a valid branch with git merge (https://git-scm.com/docs/git-merge) or git cherry-pick (https://git-scm.com/docs/git-cherry-pick) and removed from branch onceperappperenvironment@1.7.x with git revert (https://git-scm.com/docs/git-revert) or git reset (https://git-scm.com/docs/git-reset).

A valid branch could be master.

See the workflow configuration documentation (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/workflow-configuration.md) for more details.

SemanticReleaseError: The release `1.7.1` on branch `onceperappperenvironment@1.7.x` cannot be published as it is out of range.
    at module.exports (/usr/local/lib/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/usr/local/lib/node_modules/semantic-release/index.js:173:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/usr/local/lib/node_modules/semantic-release/cli.js:55:5) {
  code: 'EINVALIDNEXTVERSION',
  details: 'Based on the releases published on other branches, only versions within the range `>=1.7.0 <1.5.1` can be published from branch `onceperappperenvironment@1.7.x`.\n' +
    '\n' +
    'The following commit is responsible for the invalid release:\n' +
    '- fix(fds): fds (3c2b394)\n' +
    '\n' +
    'This commit should be moved to a valid branch with [git merge](https://git-scm.com/docs/git-merge) or [git cherry-pick](https://git-scm.com/docs/git-cherry-pick) and removed from branch `onceperappperenvironment@1.7.x` with [git revert](https://git-scm.com/docs/git-revert) or [git reset](https://git-scm.com/docs/git-reset).\n' +
    '\n' +
    'A valid branch could be `master`.\n' +
    '\n' +
    'See the [workflow configuration documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/workflow-configuration.md) for more details.',
  semanticRelease: true
}
```

I understand that this error is directly related to **semrel** so maybe I should post to them to get support, but **msr** still lacks the support for maintenance branches. see error below.

**msr** should detect the branch it's running in, and if it looks like a maintenance branch e.g `packagename@N.N.x` or `packagename@N.x` it should only run for that package to avoid the failure below.



```
:: npm run release

> test-devops@1.0.0 release ../test-devops-da
> multi-semantic-release --sequential-init

multi-semantic-release version: 2.3.0
semantic-release version: 17.1.1
flags: {
  "sequentialInit": true,
  "debug": false
}
yarn paths [
  '../test-devops/Terraform/Lambda/package.json',
  '../test-devops/Terraform/OncePerAccount/package.json',
  '../test-devops/Terraform/OncePerAppPerEnvironment/package.json',
  '../test-devops/Terraform/OncePerEnvironment/package.json'
]
[11:08:58] › 🎉  Started multirelease! Loading 4 packages...
[11:08:58] › ✔  Loaded package lambda
[11:08:58] › ✔  Loaded package onceperaccount
[11:08:58] › ✔  Loaded package onceperappperenvironment
[11:08:58] › ✔  Loaded package onceperenvironment
[11:08:58] › 🎉  Queued 4 packages! Starting release...
[11:08:58] [lambda] › ℹ  Running semantic-release version 17.1.1
[11:08:58] [lambda] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[11:08:58] [lambda] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[11:09:01] [lambda] › ℹ  This test run was triggered on the branch onceperappperenvironment@1.7.x, while semantic-release is configured to only publish from 1.0.x, 1.x, 2.0.x, master, therefore a new version won’t be published.

```

**Comment by dhoulb** [comment]
Hi @musaabal-okaidi 

This isn't a specific configuration we've tested, but I'd assume it will work the same as plain semantic-release (i.e. branches named `1.7.x` will be released to NPM with the dist-tag `@release-1.7.x`). 

We don't have any specific code to support maintenance releases for specific packages (i.e. with the format `onceperappperenvironment@1.7.x`). 

I think it's unlikely we'll add this — MSR is intended as a temporary lightweight wrapper on top of semantic-release, that can hopefully be deprecated once semantic-release support monorepos natively. Every extra custom feature adds maintenance burden and makes it more difficult for us to deprecate this package when that happens.

**Comment by musab90** [comment]
Thanks @dhoulb 

Correct me if I'm wrong, but from reading around on some of the issues on the semantic-release repo, they don't even seem to be remotely interested in supporting monorepos.

Either way, thanks for looking into this. We've got a manual process to do this and we would rarely need to use it.

**Comment by musaabal-okaidi** [comment]
Thanks @dhoulb

Correct me if I'm wrong, but from reading around on some of the issues on the semantic-release repo, they don't even seem to be remotely interested in supporting monorepos.

Either way, thanks for looking into this. We've got a manual process to do this and we would rarely need to use it.

**Comment by dhoulb** [comment]
@musaabal-okaidi 

Yes it's upsetting! I don't think semantic release will last forever. Its internals are kinda straining under the weight of what's demanded of it. 

Before long a new project will come along that does the same job but considers monorepos at a core level, and we can all switch to that instead. I dream about building it some time, and then stop myself just in time.
