### ISSUE TITLE
The "file" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by younes200** [dhoulb/multi-semantic-release#35]
Hi,
Having problem running MSR on gitlabCI, command runs fine on local. Any idea which "file" argument the exception is referring to ?

```
$ npx handpick --target=releaseDependencies && npx multi-semantic-release -d
npx: installed 26 in 3.643s
- Hand picking DIRTY releaseDependencies via NPM
✔ Hand picking DIRTY releaseDependencies via NPM
multi-semantic-release version: 2.4.5
semantic-release version: 17.1.1
flags: {
  "d": true,
  "sequentialInit": false,
  "firstParent": false,
  "debug": false
}
[multi-semantic-release]: TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at normalizeSpawnArguments (child_process.js:398:3)
    at spawnSync (child_process.js:557:16)
    at Function.spawnSync [as sync] (/builds/project/node_modules/bash-glob/node_modules/cross-spawn/index.js:46:14)
    at Function.glob.sync (/builds/project/node_modules/bash-glob/index.js:189:18)
    at /builds/project/node_modules/bash-glob/index.js:160:29
    at Array.reduce (<anonymous>)
    at Function.glob.sync (/builds/project/node_modules/bash-glob/index.js:159:20)
    at getWorkspacesYarn (/builds/project/node_modules/multi-semantic-release/lib/getWorkspacesYarn.js:26:26)
    at module.exports (/builds/project/node_modules/multi-semantic-release/bin/runner.js:22:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

```
"@semantic-release/changelog": "^5.0.1",
"@semantic-release/commit-analyzer": "^8.0.1",
"@semantic-release/git": "v9.0.0",
"@semantic-release/gitlab": "^6.0.4",
"@semantic-release/release-notes-generator": "^9.0.1",
"multi-semantic-release": "^2.4.5",
 "semantic-release": "^17.0.7"
```

```json
"release": {
    "branches": [
      "master"
    ],
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/gitlab",
      "@semantic-release/release-notes-generator"
    ],
    "verifyConditions": [
      "@semantic-release/changelog",
      "@semantic-release/git"
    ],
    "prepare": [
      "@semantic-release/changelog",
      "@semantic-release/git"
    ],
    "publish": [
      "@semantic-release/gitlab"
    ]
  }
```

Thank you.

**Comment by alyaptsev** [comment]
Hi! Having the same issue. Any updates here?

**Comment by antongolub** [comment]
**msr** uses **bash-glob** which requires `bash` to be installed. Unfortunately, there's no point where `bash-path` value is checked against `undefined`.

bash-glob/index.js
```js
var bashPath = require('bash-path');
//...
var cp = spawn(bashPath, cmd(pattern, options), options);

```
cross-spawn.index.js
```js
var cp = require('child_process');
var parse = require('./lib/parse');
var cpSpawnSync = cp.spawnSync;
//...

// Parse the arguments
parsed = parse(command, args, options);

// Spawn the child process
result = cpSpawnSync(parsed.command, parsed.args, parsed.options);
```
