### ISSUE TITLE
Cannot release because dependency xxx has not been released

### ISSUE THREAD

**Issue by bubkoo** [dhoulb/multi-semantic-release#39]
The semantic-release config is: 
```json
{
    "repositoryUrl": "https://github.com/antvis/x6",
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      [
        "@semantic-release/github",
        {
          "addReleases": "bottom"
        }
      ],
      [
        "@semantic-release/git",
        {
          "assets": ["package.json", "CHANGELOG.md"]
        }
      ]
    ]
  }
```
And get errors:

```log
[5:47:42 PM] [@antv/x6-app-er] › ✖  Failed step "generateNotes" of plugin "Inline plugin"
[5:47:42 PM] [@antv/x6-app-er] › ✖  An error occurred while running semantic-release: Error: Cannot release because dependency @antv/x6-react-components has not been released
    at /home/runner/work/X6/X6/node_modules/multi-semantic-release/lib/createInlinePluginCreator.js:50:11
    at Array.forEach (<anonymous>)
    at updateManifestDeps (/home/runner/work/X6/X6/node_modules/multi-semantic-release/lib/createInlinePluginCreator.js:44:18)
    at generateNotes (/home/runner/work/X6/X6/node_modules/multi-semantic-release/lib/createInlinePluginCreator.js:191:4)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async validator (/home/runner/work/X6/X6/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/X6/X6/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/runner/work/X6/X6/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as generateNotes] (/home/runner/work/X6/X6/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/runner/work/X6/X6/node_modules/semantic-release/index.js:183:23) {
  pluginName: 'Inline plugin'
}
[multi-semantic-release]: Error: Cannot release because dependency @antv/x6-react-components has not been released
    at /home/runner/work/X6/X6/node_modules/multi-semantic-release/lib/createInlinePluginCreator.js:50:11
    at Array.forEach (<anonymous>)
    at updateManifestDeps (/home/runner/work/X6/X6/node_modules/multi-semantic-release/lib/createInlinePluginCreator.js:44:18)
    at generateNotes (/home/runner/work/X6/X6/node_modules/multi-semantic-release/lib/createInlinePluginCreator.js:191:4)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async validator (/home/runner/work/X6/X6/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/X6/X6/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/runner/work/X6/X6/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as generateNotes] (/home/runner/work/X6/X6/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/runner/work/X6/X6/node_modules/semantic-release/index.js:183:23) {
  pluginName: 'Inline plugin'
}
error Command failed with exit code 1.
```

**Comment by antongolub** [comment]
Hey, @bubkoo,

**msr** verifies that all required packages have been released previously (repo has proper tag) or would be released in the current release session. You should make some meaningful changes to trigger a release for all chained packages or just to trick **msr** and attach `@scope/required-package@1.0.0` to any previous commit.

**Comment by bubkoo** [comment]
@antongolub thks for your reply.
